// JnA_assessment/src/components/Header.vue
<template>
  <div class="header d-flex justify-content-between align-items-center mb-3 mt-5">
    <!-- Left side: title + subtitle -->
    <div>
      <h3 class="header-title mb-4">Your Resources</h3>
      <p class="header-subtitle">You may add more or edit your existing resources</p>
    </div>

    <!-- Right side: action icons -->
    <div class="header-actions d-flex align-items-center gap-3">
      <i class="bi bi-pencil"></i>
      <i class="bi bi-plus-lg"></i>
      <i class="bi bi-list-ul"></i>
      <i class="bi bi-arrow-down-up"></i>
    </div>
  </div>
</template>

<style scoped>
.header-title {
  font-weight: 600;
  color: #1d4ed8;
  margin: 0;
  font-size: 2rem;
}

.header-subtitle {
  font-size: 1.25rem;
  color: #6b7280;
  margin: 0;
}

.header-actions i {
  font-size: 1.5rem;
  font-weight: bold;
  padding: 0.5rem;
  border-radius: 50%;
  transition: background 0.2s ease, color 0.2s ease;
  cursor: pointer;
}

.header-actions i:hover {
  background-color: #dbeafe;
  color: #1d4ed8;
}

</style>

// JnA_assessment/src/components/Lit_components/Header-Lit.js
import { LitElement, html, css } from "lit";
import 'bootstrap-icons/font/bootstrap-icons.css';

export class HeaderLit extends LitElement {
  static properties = {
    title: { type: String },
    subtitle: { type: String },
  };

  createRenderRoot() {
    const root = super.createRenderRoot();
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css';
    root.appendChild(link);
    return root;
  }

  constructor() {
    super();
    this.title = "Placeholder Resources";
    this.subtitle = "Placeholder - You may add more or edit your existing resources";
  }

  static styles = css`
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
      margin-top: 2rem;
    }

    .header-title {
      font-weight: 600;
      color: #1d4ed8;
      margin: 0;
      font-size: 2rem;
    }

    .header-subtitle {
      font-size: 1.25rem;
      color: #6b7280;
      margin: 0;
    }

    .header-actions {
      display: flex;
      align-items: center;
      gap: 1rem;
    }

    .header-actions i {
      font-size: 1.5rem;
      font-weight: bold;
      padding: 0.5rem;
      border-radius: 50%;
      transition: background 0.2s ease, color 0.2s ease;
      cursor: pointer;
    }

    .header-actions i:hover {
      background-color: #dbeafe;
      color: #1d4ed8;
    }
    @media (max-width: 768px) {
      .header {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        margin-bottom: 1rem;
        margin-top: 2rem;
      }

      .header-text {
        display: flex;
        flex-direction: column;
        text-align:center;
      }

      .header-title {
        font-weight: 600;
        color: #1d4ed8;
        margin: 0;
        font-size: 2rem;
        text-align:center;
      }

      .header-subtitle {
        font-size: 1.25rem;
        color: #6b7280;
        margin: 0;
        text-align:center;
      }

      .header-actions {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 1rem;
      }

      .header-actions i {
        font-size: 1.5rem;
        font-weight: bold;
        padding: 0.5rem;
        border-radius: 50%;
        transition: background 0.2s ease, color 0.2s ease;
        cursor: pointer;
      }

      .header-actions i:hover {
        background-color: #dbeafe;
        color: #1d4ed8;
      }
    }
  `;

  render() {
    return html`
      <div class="header">
        <!-- Left side -->
        <div>
          <h3 class="header-title">${this.title}</h3>
          <p class="header-subtitle">${this.subtitle}</p>
        </div>

        <!-- Right side -->
        <div class="header-actions">
          <i class="bi bi-pencil"></i>
          <i class="bi bi-plus-lg"></i>
          <i class="bi bi-list-ul"></i>
          <i class="bi bi-arrow-down-up"></i>
        </div>
      </div>
    `;
  }
}

customElements.define("header-lit", HeaderLit);
