// JnA_assessment/src/components/Lit_components/Filter-Lit.js
import { LitElement, html, css } from "lit";

export class FilterLit extends LitElement {
  static properties = {
    title: { type: String },
    value: { type: String },
    modelValue: { type: String },
    id: { type: String },
    isHovered: { type: Boolean, state: true }
  };

  constructor() {
    super();
    this.title = "";
    this.value = "";
    this.modelValue = "";
    this.id = "";
    this.isHovered = false;
  }

  static styles = css`
    .btn {
      padding: 0.5rem 1rem;
      font-weight: 500;
      border-width: 1.5px;
      transition: all 0.2s ease-in-out;
      font-size: 1.3rem;
      border-radius: 50px; /* pill style */
      border: 1.5px solid #ccc;
      cursor: pointer;
      user-select: none;
      display: inline-block;
    }

    input[type="radio"] {
      display: none;
    }

    input[type="radio"]:checked + label {
      background-color: #dbeafe;
      color: #1d4ed8;
      border-color: #dbeafe;
    }

    input[type="radio"]:checked + label::before {
      content: "✓ ";
      font-weight: bold;
    }

    /* Hovered state as a class */
    .btn.hovered {
      background-color: #f0f9ff;
      border-color: #93c5fd;
      color: #1e3a8a;
    }
  `;

  onChange() {
    this.dispatchEvent(
      new CustomEvent("filter-toggled", {
        detail: this.value,
        bubbles: true,
        composed: true
      })
    );
  }

  toggleHover(e) {
    const label = this.renderRoot.querySelector("label");
    if (e.type === "mouseover") {
      label.classList.add("hovered");
    } else {
      label.classList.remove("hovered");
    }
  }

  render() {
    return html`
      <div class="btn-group" role="group">
        <input
          type="radio"
          id=${this.id}
          name="filter"
          value=${this.value}
          ?checked=${this.modelValue === this.value}
          @change=${this.onChange}
        />
        <label
          class="btn"
          for=${this.id}
          @mouseover=${this.toggleHover}
          @mouseout=${this.toggleHover}
        >
          ${this.title}
        </label>
      </div>
    `;
  }
}

customElements.define("filter-lit", FilterLit);

// JnA_assessment/src/components/Filter.vue
<script setup>
const props = defineProps({
  title: String,
  value: String,
  modelValue: String,
  id: String
})
const emit = defineEmits(['update:modelValue'])
</script>

<template>
  <div class="btn-group" role="group">
    <input
      type="radio"
      class="btn-check"
      :id="id"
      :value="value"
      :checked="modelValue === value"
      @change="$emit('update:modelValue', value)"
    />
    <label class="btn btn-outline-secondary rounded-pill me-2" :for="id">
      {{ title }}
    </label>
  </div>
</template>


<style scoped>
.btn {
  padding: 0.5rem 1rem;
  font-weight: 500;
  border-width: 1.5px;
  transition: all 0.2s ease-in-out;
  font-size: 1.3rem;
}

.btn-check:checked + .btn {
  background-color: #dbeafe;
  color: #1d4ed8;
  border-color: #dbeafe;
}

.btn-check:checked + .btn::before {
  content: "✓ ";
  font-weight: bold;
}

.btn:hover {
  background-color: #f0f9ff;
  border-color: #93c5fd;
  color: #1e3a8a;
  cursor: pointer;
}
</style>
